x-service-common: &service-common
  image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-vacancy-parser:latest
  env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
  networks:
    - app-network

x-healthcheck-common: &healthcheck-common
  interval: 30s
  timeout: 7s
  retries: 3
  start_period: 7s

services:
  vacancy-parser:
    <<: *service-common
    container_name: vacancy-parser
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://vacancy-parser:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      <<: *healthcheck-common

  vacancy-parser-worker:
    <<: *service-common
    container_name: vacancy-parser-worker
    command: [ "celery", "-A", "celery_app.app", "worker", "-n", "vacancy_parser", "-l", "${LOG_LEVEL}" ]
    cpus: 1
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_app.app inspect ping -d celery@vacancy_parser" ]
      <<: *healthcheck-common

  vacancy-parser-beat:
    <<: *service-common
    container_name: vacancy-parser-beat
    command: [ "celery", "-A", "celery_app.app", "beat", "-l", "${LOG_LEVEL}" ]
