x-service-common: &service-common
  image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-telegram-bot:latest
  env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
  networks:
    - app-network

x-healthcheck-common: &healthcheck-common
  interval: 30s
  timeout: 15s
  retries: 3
  start_period: 7s

services:
  telegram-bot:
    <<: *service-common
    container_name: telegram-bot
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://telegram-bot:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      <<: *healthcheck-common

  telegram-bot-worker:
    <<: *service-common
    container_name: telegram-bot-worker
    command: [ "celery", "-A", "celery_app.app", "worker", "-n", "telegram_bot", "--pool", "solo", "-l", "${LOG_LEVEL}" ]
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_app.app inspect ping -d celery@telegram_bot" ]
      <<: *healthcheck-common
