name: ${ENV_PROJECT_NAME}

services:
  postgres:
    extends:
      service: postgres
      file: postgres/docker-compose.yml

  pgbouncer:
    extends:
      service: pgbouncer
      file: pgbouncer/docker-compose.yml
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    extends:
      service: redis
      file: redis/docker-compose.yml

  api-gateway:
    extends:
      service: api-gateway
      file: api-gateway/docker-compose.yml

  gpt-api:
    extends:
      service: gpt-api
      file: gpt-api/docker-compose.yml

  scraper-api:
    extends:
      service: scraper-api
      file: scraper-api/docker-compose.yml

  telegram-bot-migrator:
    profiles:
      - migrator
    extends:
      service: telegram-bot
      file: telegram-bot/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  telegram-bot:
    extends:
      service: telegram-bot
      file: telegram-bot/docker-compose.yml
    depends_on:
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy

  telegram-bot-worker:
    extends:
      service: telegram-bot-worker
      file: telegram-bot/docker-compose.yml
    depends_on:
      telegram-bot:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      vacancy-processor:
        condition: service_healthy

  vacancy-parser-migrator:
    profiles:
      - migrator
    extends:
      service: vacancy-parser
      file: vacancy-parser/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  vacancy-parser:
    extends:
      service: vacancy-parser
      file: vacancy-parser/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      scraper-api:
        condition: service_healthy

  vacancy-parser-worker:
    extends:
      service: vacancy-parser-worker
      file: vacancy-parser/docker-compose.yml
    depends_on:
      vacancy-parser:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy

  vacancy-parser-beat:
    extends:
      service: vacancy-parser-beat
      file: vacancy-parser/docker-compose.yml
    depends_on:
      redis:
        condition: service_healthy

  vacancy-processor-migrator:
    profiles:
      - migrator
    extends:
      service: vacancy-processor
      file: vacancy-processor/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  vacancy-processor:
    extends:
      service: vacancy-processor
      file: vacancy-processor/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      gpt-api:
        condition: service_healthy

  vacancy-processor-worker:
    extends:
      service: vacancy-processor-worker
      file: vacancy-processor/docker-compose.yml
    depends_on:
      vacancy-processor:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      gpt-api:
        condition: service_healthy

  vacancy-processor-beat:
    extends:
      service: vacancy-processor-beat
      file: vacancy-processor/docker-compose.yml
    depends_on:
      redis:
        condition: service_healthy

  vacancy-matcher:
    extends:
      service: vacancy-matcher
      file: vacancy-matcher/docker-compose.yml
    depends_on:
      vacancy-processor:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  flower-data:
