name: ${ENV_PROJECT_NAME}

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    env_file: ../.env
    command: -p ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}", "-p", "${DB_PORT}" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: pgbouncer
    env_file: ../.env
    environment:
      - AUTH_TYPE=scram-sha-256
      - LISTEN_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${DB_HOST}", "-p", "${DB_PORT}"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    env_file: ../.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--port", "${REDIS_PORT}" ]
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s

  flower:
    image: mher/flower
    container_name: flower
    env_file: ../.env
    environment:
      CELERY_BROKER_URL: "redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_CELERY_BROKER_DB}"
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    volumes:
      - flower-data:/data
    command: [ "celery", "flower", "--port=${FLOWER_PORT}", "-l", "${LOG_LEVEL}" ]
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  api-gateway:
    extends:
      service: api-gateway
      file: api-gateway/docker-compose.yml

  gpt-api:
    extends:
      service: gpt-api
      file: gpt-api/docker-compose.yml

  telegram-api:
    extends:
      service: telegram-api
      file: telegram-api/docker-compose.yml

  telegram-bot-migrator:
    profiles:
      - migrator
    extends:
      service: telegram-bot
      file: telegram-bot/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  telegram-bot:
    extends:
      service: telegram-bot
      file: telegram-bot/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy

  telegram-bot-worker:
    extends:
      service: telegram-bot-worker
      file: telegram-bot/docker-compose.yml
    depends_on:
      telegram-bot:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      vacancy-processor:
        condition: service_healthy

  vacancy-parser-migrator:
    profiles:
      - migrator
    extends:
      service: vacancy-parser
      file: vacancy-parser/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  vacancy-parser:
    extends:
      service: vacancy-parser
      file: vacancy-parser/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      telegram-api:
        condition: service_healthy

  vacancy-parser-worker:
    extends:
      service: vacancy-parser-worker
      file: vacancy-parser/docker-compose.yml
    depends_on:
      vacancy-parser:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy

  vacancy-parser-beat:
    extends:
      service: vacancy-parser-beat
      file: vacancy-parser/docker-compose.yml
    depends_on:
      redis:
        condition: service_healthy

  vacancy-processor-migrator:
    profiles:
      - migrator
    extends:
      service: vacancy-processor
      file: vacancy-processor/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy

  vacancy-processor:
    extends:
      service: vacancy-processor
      file: vacancy-processor/docker-compose.yml
    depends_on:
      pgbouncer:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      gpt-api:
        condition: service_healthy

  vacancy-processor-worker:
    extends:
      service: vacancy-processor-worker
      file: vacancy-processor/docker-compose.yml
    depends_on:
      vacancy-processor:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      gpt-api:
        condition: service_healthy

  vacancy-processor-beat:
    extends:
      service: vacancy-processor-beat
      file: vacancy-processor/docker-compose.yml
    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres-data:
  redis-data:
  flower-data: