services:
  gpt-api:
    container_name: gpt-api
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-gpt-api:latest
    env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://gpt-api:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 5s
      start_interval: 1s
