x-service-common: &service-common
  image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-vacancy-processor:latest
  env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
  networks:
    - app-network

x-healthcheck-common: &healthcheck-common
  interval: 30s
  timeout: 7s
  retries: 3
  start_period: 7s

services:
  vacancy-processor:
    <<: *service-common
    container_name: vacancy-processor
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://vacancy-processor:${ENV_SERVICE_INTERNAL_PORT}/health" ]
      <<: *healthcheck-common

  vacancy-processor-worker:
    <<: *service-common
    container_name: vacancy-processor-worker
    command: [ "celery", "-A", "celery_app.app", "worker", "-n", "vacancy_processor", "--pool", "solo", "-l", "${LOG_LEVEL}" ]
    healthcheck:
      test: [ "CMD-SHELL", "celery -A celery_app.app inspect ping -d celery@vacancy_processor" ]
      <<: *healthcheck-common

  vacancy-processor-beat:
    <<: *service-common
    container_name: vacancy-processor-beat
    command: [ "celery", "-A", "celery_app.app", "beat", "-l", "${LOG_LEVEL}" ]
