services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    env_file: ${SERVICE_PROJECT_ROOT}/infra/.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--port", "${REDIS_PORT}" ]
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s