# $schema: https://json.schemastore.org/github-workflow.json

name: Building

on:
  workflow_call:

env:
  ENV_MODE: production

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        service: [api-gateway, gpt-api, scraper-api, telegram-bot, vacancy-parser, vacancy-processor]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.ENV_DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./infra/docker/${{ matrix.service }}/Dockerfile
          tags: ${{ vars.ENV_DOCKER_USERNAME }}/${{ vars.ENV_PROJECT_NAME }}-${{ matrix.service }}:latest
          cache-from: type=registry,ref=${{ vars.ENV_DOCKER_USERNAME }}/${{ vars.ENV_PROJECT_NAME }}-${{ matrix.service }}:cache
          cache-to: type=registry,ref=${{ vars.ENV_DOCKER_USERNAME }}/${{ vars.ENV_PROJECT_NAME }}-${{ matrix.service }}:cache,mode=max

      - name: Notify Telegram on Failure
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Build
          title: ❌ Build Failure ❌
          to: ${{ secrets.TELEGRAM_NOTIFIER_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFIER_BOT_TOKEN }}
