# $schema: https://json.schemastore.org/github-workflow.json

name: Linting

on:
  workflow_call:

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.4"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: make venv-style

      - name: Check Linting and Formating
        run: make lint

      - name: Send Telegram Notification
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Linting
          title: ❌ Lint Failure ❌
          to: ${{ secrets.TELEGRAM_NOTIFIER_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFIER_BOT_TOKEN }}
